version: '3'

services:
  appdb:
    image: sachiniw/movie-db:latest
    ports:
      - 3307:3306
    network_mode: bridge

  app:
    image: sachiniw/movie-app:latest
    ports:
      - 8080:8080
    depends_on:
      - appdb
    network_mode: bridge
    links:
      - "appdb:sachiniw/movie-db"